language: php

addons:
  apt:
    packages:
      - libuv1-dev
      - php-pear

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    allow_failures:
        - php: 7.3
        - php: 7.4
    fast_finish: true

before_script:
    - pecl channel-update pecl.php.net
    - pecl install uv-beta
    - composer install

after_success:
    - bash <(curl -s https://codecov.io/bash)

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml
