# GitHub Action for PHP with extensions
name: Spawn

on: [push, pull_request]

jobs:
  linux7-4:
    name: Linux CI 7.4
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'
          extensions: mbstring, simplexml, dom, xdebug
          coverage: xdebug
      - name: Install libuv and PHP build tools
        run: |
          sudo apt update
          sudo apt-get install libuv1-dev php-pear
      - name: Build and install PHP-UV extension
        run: |
          sudo pecl channel-update pecl.php.net
          sudo pecl install uv-beta
      - name: Add uv.so to php.ini
        run: sudo echo "extension=uv.so" >> "$(php -r 'echo php_ini_loaded_file();')"
      - name: Install dependencies
        run: composer install
      - name: Test with phpunit
        run: vendor/bin/phpunit -d zend.enable_gc=0 --coverage-clover=coverage/phpunit/clover.xml
      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)

  windows:
    name: Windows CI
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        php: ['7.3']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        tools: pecl
        extensions: mbstring, simplexml, curl, dom, sockets, fileinfo, openssl, xdebug, uv-beta
        coverage: xdebug
      env:
        PHPTS: ts # specify ts or nts
    - name: Download and install PHP-UV
      shell: powershell
      run: |
        cd C:\tools\php
        Invoke-WebRequest "https://windows.php.net/downloads/pecl/releases/uv/0.2.4/php_uv-0.2.4-7.3-ts-vc15-x64.zip" -OutFile "php_uv-0.2.4-7.3-ts-vc15-x64.zip"
        7z x -y php_uv-0.2.4-7.3-ts-vc15-x64.zip libuv.dll php_uv.dll
        copy php_uv.dll ext\php_uv.dll
        del php_uv.dll
        del php_uv-0.2.4-7.3-ts-vc15-x64.zip
    - name: Install dependencies
      run: composer install
    - name: Test with phpunit
      run: vendor\bin\phpunit --coverage-clover=coverage/phpunit/clover.xml
    - name: Submit code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
